### ISSUE TITLE
앱꺼짐

### ISSUE THREAD

**Issue by sicasica** [PYTHONKOR/alltv#1]
쉴드tv에 설치하고 설정에서 로그인 정보를 넣고 설정 저장을 누르면 앱이 종료되고 입력해둔 값은 초기화되어 앱을 사용할 수 없습니다.

**Comment by PYTHONKOR** [comment]
혹시 암호에 "&" 특수 문자가 포함되어 있으신가요??
해당 문자가 암호에 포함되어 있으면 현재 크래쉬가 나고 있습니다.
관련해서 확인 부탁드립니다.

또한 설정 저장 클릭 이후에 계속 앱 실행에 문제가 생기신다면,
쉴드TV -> 앱 -> ALL TV -> 내부데이터 삭제를 통해 저장된 정보를
지우면 실행 가능합니다.

그리고 설치하신 버전이 1.2가 맞는지 확인도 해보셔야 합니다.
https://github.com/PYTHONKOR/alltv/releases/tag/1.2

추후에 관련 문제 수정 예정입니다.

**Comment by sicasica** [comment]
비밀번호에 특수 문자 "#" 가 포함되어 있어도 동일한 현상이 발생하네요.
비밀번호에서 특수문자 "#" 이 제외되게 했을 경우 잘 동작합니다.
추후 수정 해당 사항도 확인해보시면 좋을 것 같습니다.

**Comment by sicasica** [comment]
비밀번호에 특수 문자 "#" 가 포함되어 있어도 동일한 현상이 발생하네요.
비밀번호에서 특수문자 "#" 이 제외되게 했을 경우 잘 동작합니다.
추후 수정 해당 사항도 확인해보시면 좋을 것 같습니다.

**Comment by PYTHONKOR** [comment]
답변 감사합니다. &, # 등과 같이 웹 주소 표현관련 특수 문자일 경우
현재 문제가 발생하고 있습니다.

관련하여 수정해야 겠네요.

소중한 리포팅 감사드립니다.

**Comment by PYTHONKOR** [comment]
1.3 버전에서 관련 사항 수정 완료

https://github.com/PYTHONKOR/alltv/releases/tag/1.3
