### ISSUE TITLE
1.5 버전에서 옥수수 로그인이 불가능합니다.

### ISSUE THREAD

**Issue by vitamin2167** [PYTHONKOR/alltv#10]
1.4 버전에서는 문제없이 사용 중이었으나.

1.5 버전부터는 옥수수 로그인이 불가능 합니다.

사용 기기 : 뷰잉

옥수수 푹 둘다 비밀번호 특수문자 들어갑니다.
푹은 문제없이 로그인 되어 사용 가능하나 
옥수수는 로그인이 안되어 사용이 불가능합니다.

조금 이상한점은 1.5 버전으로 원래 잘 사용 중이였으나
갑자기 앱이 실행이 불가능하게 된후 (실행후 먹통)
1.5 버전  재설치후 실행은 가능해졌으나 옥수수티비 로그인이 불가능 합니다.

현재 1.4 버전으로 아무 문제없이 사용중입니다.

---------------------------------------------------------

너무 잘 만들어주셔서 실시간 티비 잘 보고 있습니다
항상 감사하게 생각하고 응원하고 있습니다.

현재 1.4 버전으로 낮춰서 사용중입니다.

천천히 시간 되실때 확인 한번 부탁드리겠습니다 !

**Comment by suikano1304** [comment]
동일한 현상 발생합니다. 기존에 1.3버전 사용했을 때 이상 없었습니다.
사용환경은 Shield TV 사용 중이며 옥수수 로그인 (최초 세팅)시도 시 프로그램 강제종료 현상 발생합니다. 풐은 문제 없이 로그인 가능합니다. 전 오늘 설치해서 몰랐는데 vitamin님께서 말씀 하시는 걸 보니 금일 옥수수쪽에 로그인 관련해서 로직이 변경되었거나 했을지도 모르겠다는 생각이 드네요. 일단 1.4 버전 설치해서 사용 해 보려고 합니다. 비도 많이 오고 후덥지근한데 부디 즐거운 주말 되시길 바랍니다.

추가. 동일하게 1.4 버전에선 문제없이 로그인 가능 확인 했습니다. 저는 비번에 특수문자 포함되어있지 않습니다.

**Comment by PYTHONKOR** [comment]
우선 1.5 버전에서 로그인 로직에서 다른 분들에 기여 코드가 반영되었는데,
관련해서 체크해 봐야겠네요.

**Comment by vitamin2167** [comment]
현재 1.2 / 1.3 / 1.4 / 1.5 버전 전부다 옥수수 티비 로그인 시 오류가 발생 합니다.

1.2 - 1.4 버전은 옥수수 티비 로그인시 로그인은 가능하나 재생시 팅김 현상 발생중이고.

1.5 버전은 옥수수 티비 로그인시 아에 앱실행 자체가 불가 합니다.

푹티비는 재생및 로그인 다 가능합니다.


* 현재 1.5 버전 재설치 후 옥수수티비 로그인은 하지 않고 푹티비만 로그인 해서
사용 하고 있습니다.


옥수수 티비 푹 티비 계정은 사이트 자체 가입 아이디 입니다.


1.3 버전부터 1.5버전 까지 아무 문제 없이 잘 쓰다가
어제 저녁부터 이런 증상이 발생 하는거 같습니다

**Comment by PYTHONKOR** [comment]
혹시 옥수수 사용하는 계정이 옥수수 사이트 자체 가입 아이디 인가요?
아니면, 소셜 로그인 형태의 아이디를 쓰시는 건가요??

**Comment by PYTHONKOR** [comment]
To @vitamin2167 우선, 버그 추적에 좋은 정보들 감사합니다.

현재 저의 옥수수 계정(유료,자체가입)으로는 전혀 문제가 발생하지 않고 있네요. :worried:
적어주신 내용으로 의심이 가는 부분은 문제 발생 시점쯔음에 옥수수 측에서 로그인 로직이나
처리가 변경된 것으로 보입니다.

혹시 문제 추적을 위해서 아이디와 암호를 저에게 공유 가능하신가요?
공유해주신다면 오직 문제 추적을 위해서만 사용하도록 하겠습니다.

**Comment by vitamin2167** [comment]
헐... 해결 되었습니다.

PYTHONKOR  님에게 비번 공유 하려고 비밀 번호 변경 했는데.

혹시나 싶어서 바뀐 비번으로 로그인 하니까 아무 문제 없이 예전 처럼 사용 가능합니다

**Comment by PYTHONKOR** [comment]
kisi3@hanmail.net 입니다. 개인메일이므로 여기로 보내주시면 됩니다.

그리고 문제추적후에 다시 답 메일로 사용완료했다고 보내드릴께요.

**Comment by PYTHONKOR** [comment]
혹시 에러가 나는 시기에 사용했던 암호에 특수문자를 사용했다고 하셨는데,
어떤 특수문자가 사용되었는지 알려주실 수 있으신가요??

아마도 앱에서 특수문자 처리에서 문제가 발생한 것 같아서요.

**Comment by vitamin2167** [comment]
@ 특수문자가 들어갔었고 

혹시나 해서 원래 쓰던 @ 들어간 비번으로 다시 변경 해서 로그인 하여 사용 중인데 
아무 이상 없이 잘되고 있습니다

**Comment by PYTHONKOR** [comment]
이전에 특수문자 에러 처리를 했는데, 역시 특수문자 문제는 아니겠네요.
우선은 현재 소스에서 로그인시와 비디오 주소 얻기시에 문제 발생히
최소한 크래쉬를 발생하지 않도록 하는 작업을 추가중에 있습니다.(1.6 버전이 되겠네요.)

그럼 이 이슈는 닫도록 하겠습니다.

**Comment by vitamin2167** [comment]
네 감사합니다 ^^ 다음 업데이트도 기대하고 있습니다 항상 감사한 마음으로 잘 쓰고 있습니다

**Comment by suikano1304** [comment]
저도 동일하게 문제 해결되었습니다. 새벽간에 옥수수측에서 뭔가 작업을 하지 않았나 추측되네요. 전 비밀번호 변경하지 않고 정상적으로 로그인 완료 되었습니다.

**Comment by vitamin2167** [comment]
새벽 5시 19분 또 같은 증상이네요 ㅠ.ㅠ 하.. 당분간 옥수수티비 로그인은 하면 안될듯 싶네요.
