### ISSUE TITLE
옥수수 TV 로그인시 앱 팅김 형상이 재발생 됩니다 

### ISSUE THREAD

**Issue by vitamin2167** [PYTHONKOR/alltv#11]
어제 이슈 해결후 
금일 새벽 5시 경 다시 같은 증상입니다.

ALLTV 애플리케이션 실행 불가  - 앱 재설치 후 - 옥수수 티비 로그인시 앱 팅김 

현재  앱 재설치후 폭티비만 로그인해서 사용 하고 있습니다.

 

어제와 같은 방법으로 비밀번호 변경후 다시 로그인 시도 해보았지만
해결이 안되네요. 

저의 티비박스 문제인거 같아서 혹시나 해서 초기화 까지 해보았으나
증상은 똑같습니다.

혹시나 저의 옥수수티비 계정 정보가 필요하시다면
이메일 남겨주시면 바로 보내드리도록 하겠습니다 

사용중인 단말기 : 뷰잉
로그인시 들어간 특수문자 : @ 
옥수수티비 계정 종류 : 소셜계정이 아닌 자체 가입 계정입니다.

**Comment by hoonsoft** [comment]
미박스 이용자인데 저도 옥수수에서 같은 문제 발생하네요. 1.4에서는 정상 작동하는 듯 합니다. 1.5랑 1.6버전에서는 옥수수 들어가면 계속 앱이 꺼지네요

**Comment by PYTHONKOR** [comment]
우선 새벽에 뭔가 옥수수측에서 작업을 하는 것 같아 보이는데,(새로운 서비스와 관련해서)
따로 계정 구분을 하는 것 같지는 않고요. 어떤 계정이든 에러가 발생하는 것으로 보입니다.

빠른 시일안에 수정해 보도록 해야겠네요.

**Comment by PYTHONKOR** [comment]
그리고 참고로 문제 발생시 앱을 다시 지우거나 재설치 안하고
안드tv -> 설정에서 앱으로 들어가서 ALL TV 선택하고 캐쉬나, 내부 데이터 삭제 누르시면
됩니다.

**Comment by suikano1304** [comment]
> 그리고 참고로 문제 발생시 앱을 다시 지우거나 재설치 안하고
> 안드tv -> 설정에서 앱으로 들어가서 ALL TV 선택하고 캐쉬나, 내부 데이터 삭제 누르시면
> 됩니다.

1.4 미만에선 정상 작동 / 1.5 버전 이상에선 새벽 12~1시경을 시작으로 4~5시경 까지 동일 현상 지속 발생하는 듯 합니다. 앱 재설치 안하고도 다음날 되면 정상 작동됨을 확인 하였습니다. 현재 시간 기준 1.6버전 튕김현상 발생 합니다.

**Comment by PYTHONKOR** [comment]
네 저도 자정부터 새벽시간에 앱 크래쉬 현상이 나오네요.
빠른 시일안에 수정될 예정입니다.

**Comment by PYTHONKOR** [comment]
관련하여 크래쉬를 수정하였습니다.

문제 발생 원인은 옥수수에만 한정되며,
옥수수 사이트에서 편성 정보를 가져오는 중에 아무것도 없을시에 예외처리가 없어서
크래쉬가 발생하였네요.(주로 방송이 끝나는 자정에서 새벽시간대에 발생하였습니다.)

최신 버전 1.7로 업데이트 하시면 됩니다.
문제 있으셨던 분들중에서 최신 버전으로 업데이트하여( 1.7버전) 
자정~새벽시간대에 문제 없는지 피드백 남겨주시면 감사합니다.

이 이슈는 좀 더 지켜보고 닫도록 하겠습니다.

**Comment by vitamin2167** [comment]
금일 설치하였고 8/1일 새벽 1:26분 기준 문제 없이 잘되고 있습니다.

늦은 새벽 시간대 재확인하여 다시 한번 피드백 남기도록 하겠습니다.

빠른 업데이트 감사합니다 ^^
