### ISSUE TITLE
채널 변경 버튼을 DPAD_UP ,DOWN 버튼 외 채널 변경버튼으로 가능했으면 합니다

### ISSUE THREAD

**Issue by vitamin2167** [PYTHONKOR/alltv#13]
이번 1.9 대대적인 업데이트 정말 마음에 드네요 ㅎ

버그 픽스도 빠르고 정말 감사하게 잘 쓰고 있습니다.

현재 채널 변경도 DPAD_UP,DOWN  버튼으로도 가능한데.

뷰잉에 있는 채널 UP,DOWN  버튼으로도 되면 아주 더할 나위 없이 

좋을거 같은데 이부분을 추가해주셧으면 하여 글 남겨봅니다 ㅎㅎ

버튼리매핑 앱으로 찾아보니

CHANNEL_UP  , CHANNEL_DOWN

으로 인식되는 버튼입니다 ^^;

**Comment by PYTHONKOR** [comment]
우선 피드백 감사합니다.

저도 시간이 없어 이 프로젝트를 많이 신경을 못 쓰고 있는데,
다른 분들께서 같이 기여를 해주셔서 더 개선이 되어가고 있네요.

올려주신 내용은 차후 패치에 반영될 수 있도록 노력해 보겠습니다.

**Comment by morven-ai** [comment]
깃헙을 처음 이용해봐서 글을 어떻게 남기는지 모르겠습니다...
댓글로 남겨서 우선 죄송하고 항상 감사한 마음으로 잘 사용중입니다 ㅎㅎ

1.3버전 부터 사용한 것 같은데 그때부터 항상 10-20분정도 보고있으면 멈춤혐상이 발생합니다
뒤로갔다가 다시누르면 또 10-20분가량은 괜찮구요
옥수수와 푹 모두 비슷한 현상이 발생합니다
글을 남기는게 죄송스러워서 그저 감지덕지 사용했는데
그래도 개선이 되면 좋을 것 같아 말씀드립니다

아 그리고 이번 1.9버전에서 마이채널을 등록해봤는데
일반적으로는 뒤로갔다가 바로 선택을하면 직전에 보던 채널이 선택되었는데
마이채널에서는 뒤로가면 첫 번째 채널로 선택되는 것 같습니다

덕분에 정말 잘 사용하고 있습니다 감사합니다 ㅎㅎ

**Comment by PYTHONKOR** [comment]
> 깃헙을 처음 이용해봐서 글을 어떻게 남기는지 모르겠습니다...
> 댓글로 남겨서 우선 죄송하고 항상 감사한 마음으로 잘 사용중입니다 ㅎㅎ
> 
> 1.3버전 부터 사용한 것 같은데 그때부터 항상 10-20분정도 보고있으면 멈춤혐상이 발생합니다
> 뒤로갔다가 다시누르면 또 10-20분가량은 괜찮구요
> 옥수수와 푹 모두 비슷한 현상이 발생합니다
> 글을 남기는게 죄송스러워서 그저 감지덕지 사용했는데
> 그래도 개선이 되면 좋을 것 같아 말씀드립니다
> 
> 아 그리고 이번 1.9버전에서 마이채널을 등록해봤는데
> 일반적으로는 뒤로갔다가 바로 선택을하면 직전에 보던 채널이 선택되었는데
> 마이채널에서는 뒤로가면 첫 번째 채널로 선택되는 것 같습니다
> 
> 덕분에 정말 잘 사용하고 있습니다 감사합니다 ㅎㅎ

1. 10~20분 정도 재생 문제
-> 이 부분은 가입하신 유료상품을 확인해 보세요. 각 상품별로 재생할 수 있는 화질이
다릅니다. 가입하신 상품에 맞는 적절한 화질을 선택하셔서 시청하세요.

**Comment by PYTHONKOR** [comment]
1.10  버전에 수정될 예정입니다.
