### ISSUE TITLE
login

### ISSUE THREAD

**Issue by ghost** [PYTHONKOR/alltv#14]
-

**Comment by PYTHONKOR** [comment]
이 상황에 할 수 있는 건 가지고 계신 id, pw로 직접 로그인해서
왜 안되는지 확인하는 방법밖에 없습니다.

id, pw를 테스트 목적으로 공유해 주실 수 있으면 답변 남겨주세요.

공식앱이 아니라, 직접 디버그해서 잡는 방법밖에 없습니다.

**Comment by cantex92** [comment]
네 공유해드릴 수 있습니다.
어떻게 알려드리면 될까요?

**Comment by PYTHONKOR** [comment]
--- 으로 메일 주세요.

공유해 주신 id, pw는 테스트 목적으로만 쓰고,
확인 후에는 다시 메일로 테스트 완료했다고 안내 드릴께요.

그리고 메일에 어떤 스텝으로 로그인을 했는지 좀 더 자히 적어주시면 좋습니다.

**Comment by PYTHONKOR** [comment]
40c6f0f8e3464baf2926884abcabd1d2424b9dd3

수정 완료됨.
