### ISSUE TITLE
FHD

### ISSUE THREAD

**Issue by ghost** [PYTHONKOR/alltv#15]
-

**Comment by PYTHONKOR** [comment]
답변 드립니다.

- 옥수나나 푹에서 홈쇼핑 FHD 송출을 안해서 못보는 겁니다.
- '저작권 없음'은 옥수수나 푹등에서 각 방송사와 저작권 합의가 안 되어서 못 보는 프로그램입니다. (주로 영화일 꺼에요.)

PC든 모바일이든 다 똑같은 환경입니다.
안 나오는건 안 나오는거에요. 

이 부분들은 제가 어떻게 할 수 있는 부분이 아닙니다.

**Comment by cantex92** [comment]
그렇군요 사실 화질이 낮아도 실시간으로 볼 수 있다는거에 항상 감사할 따름입니다.
좋은 앱 제작해주셔서 감사합니다 ㅎㅎ
