### ISSUE TITLE
채널 시청중 뒤로가기 문제

### ISSUE THREAD

**Issue by DrDavidKim** [PYTHONKOR/alltv#16]
사용환경 : 쉴드 TV 및 미박스3

1.9버전에서 디패드를 이용한 채널 전환이 되어 편리해졌는데
이에 반해 뒤로가기를 하면 전에는 시청했던 채널에 포커스가 위치했으나
이번 버전에서는 채널 포커스가 매번 초기화되어 불편하네요.
이 문제만 개선하면 아주 편리할 것 같아요.

**Comment by PYTHONKOR** [comment]
확인 후 다음 패치에 반영하도록 하겠습니다.

**Comment by PYTHONKOR** [comment]
1.10  버전에 수정될 예정입니다.
