### ISSUE TITLE
Pooq 로그인 문의드립니다

### ISSUE THREAD

**Issue by kjw4861321** [PYTHONKOR/alltv#18]
Pooq을 SNS 및 T아이디로 가입하고 결제 이용중이라 로그인에 실패하는데 이런 부분도 디버깅 가능할까요?

**Comment by PYTHONKOR** [comment]
POOQ 자체 가입이 아닌 소셜 로그인(SNS, T아이디)은 지원하지 않습니다.
방법이 없습니다.

**Comment by kjw4861321** [comment]
아 그렇군요 감사합니다
신규가입해서 쓰고있는데 퀄리티가 진짜 장난아니네요ㅎㅎ 티비안테나를 살 생각하고있었는데 이 앱 만들어주셔서 정말 감사합니다ㅎㅎ
