### ISSUE TITLE
All tv 오류 문의

### ISSUE THREAD

**Issue by pjs0040** [PYTHONKOR/alltv#2]
좋은 앱 감사합니다. 
앱 실행후 옥수수 들어가서 
tvn. ocn. 중화티비등 일부채널을 
보다가 타 채널로 가서 일정시간 보다가
다시 tvn 에 돌아오면 화면이 나오질 않습니다. 

옥수수가입 3000원
u5pvr 딜럭스
화질 hd. fhd. auto. 다 안됩니다. 

위 오류가 있을시 
기기 전원을 온오프하거나
앱 설정에서 설정저장을 한번 클릭하면 
다시 나옵니다. 
그리고 다시 타 채널 다녀오면 안되고요. 
 
체크 부탁드립니다 
감사합니다.

**Comment by pjs0040** [comment]
동일 기기를 쓰는 다른분들은 문제가 없다 하네요.

**Comment by PYTHONKOR** [comment]
말씀해주신 내용으로 제가 파악한 내용은 스트리밍 주소를 얻어오고 그 주소 임시 저장을 해서
재생을 하는데, 일정 시간 이상이 지나면 그 스트리밍 주소가 무효화가 되어 버리는 것 같습니다.

완전한 방법은 아니지만 현재 버전에서 이 문제를 우회하고 싶으시다면, 
화면이 안 나올때 메인화면에서 안드 TV용 리모컨에서 뒤로가기 키를 눌러
앱이 종료되게 하시고 다시 실행하시면 메인화면에서 인증 처리 등을 다시 하게 되어
다시 시청이 가능하실 겁니다. 우선은 이 방법을 한 번 시도해 보시면 좋을 것 같습니다.

그리고 제가 시간이 날 때, 임시 저장된 스트리밍 주소 처리에 대한 작업을 진행해보도록
하겠습니다. (특정 시간마다 다시 스트리밍 주소를 얻어 오는 방법)

아시다시피 공식앱이 아니라서 약간의 치팅을 통해 구동되는 방식입니다.
물론 제가 할 수 있는 선에서 수정이나 개선을 시도하겠지만
원활한 동작에 대해서는 저도 100% 보장을 할 수 없음을 인지 부탁드립니다.

**Comment by pjs0040** [comment]
감사합니다. 
현재만으로도 충분하고도 훌륭한 앱입니다. 
약간의 불편함은 아무것도 아닙니다. 
친절한 안내 다시 한번 감사드립니다.

**Comment by PYTHONKOR** [comment]
관련하여 1.4 버전에서 문제를 수정하였습니다.

기회되시면 업데이트 해보세요.
