### ISSUE TITLE
WAVVE 서비스 변경및 옥수수 티비 서비스 종료 그리구 리모컨 인식 관련 건의드립니다.

### ISSUE THREAD

**Issue by vitamin2167** [PYTHONKOR/alltv#20]
pooq - wavve 서비스로 변경 및 옥수수TV 서비스 종료 관련해서
업데이트 예정 있으신지 궁금합니다 ^^;

아 그리고 

현재 쉴드TV 리모컨이 볼륨조절이 불편해서 
대체 안드라이드 리모컨인 RC02F라는 모델을 사용중인데

안드로이드리모컨은 보통 OK 버튼이 ENTER 라는 키로 적용이 되어있습니다.
쉴드티비의 OK 버튼은 DPAD_OK 라는 버튼으로 적용이 되어 있구요.
가끔 특정어플에서 ENTER 키가 DPAD_OK 역활을 하지 못해 조금 불편했었는데

ALLTV 앱도 보니까 채널목록에서 ENTER 버튼이 먹히지 않고 
DPAD_OK 버튼으로만 인식 되는 현상이 있습니다.

혹시나 차후 업데이트에서 ENTER 입력도 DPAD_OK 버튼과 동일한 기능으로 쓸수있도록
수정 가능한지 궁금합니다.

감사합니다 !!

**Comment by PYTHONKOR** [comment]
1. 현재 @HISONA 님이 기여해주신 부분이 반영되면,
옥수수 -> 종료
푹 -> 웨이브
티빙 새로 추가

위 형태로 변경될 예정입니다.

2. 키 관련 부분은 확인후에 수정해 보도록 하겠습니다.

**Comment by vitamin2167** [comment]
키 관련 부분 금일 쉴드TV 익스페리언스 8.01 버전업 되면서

수정이 되었습니다. 

아마 외국에서도 지속적으로 발생하던 이슈라서 그런지 수정 해주었네요 !! ㅎㅎ
