### ISSUE TITLE
Wavve 특정 채널 재생 안됨 관련 문의

### ISSUE THREAD

**Issue by suikano1304** [PYTHONKOR/alltv#21]
현재 Alltv 2.0버전에서 Wavve서비스 실행 시, 홈쇼핑, 예능다시보기(ex.무한도전) 채널 등 많은 수의 채널이 정상 재생이 안됩니다.

채널을 켤 경우 wavve오류(?) 표시가 나오면서 재생이 안되네요. 기타 장비 (아이패드 등)에서는 정상 플레이가 가능함을 확인 했습니다.

**Comment by PYTHONKOR** [comment]
적어주신 글을 천천히 읽어봐도 문제가 있다는 얘기는 알겠는데,
정확히 어떤 부분을 얘기하시는지 모르겠습니다.
글 내용만으로는 도저히 제가 어떻게 해볼 수 있는 방법이 없습니다.

https://github.com/PYTHONKOR/alltv/issues/9

위 글을 참고하시어 자세한 내용을 적어주세요.
