### ISSUE TITLE
EBS 2 채널 FHD 화질에서 재생되지 않는 부분 신고

### ISSUE THREAD

**Issue by ganoyi** [PYTHONKOR/alltv#23]
사용환경 : 미박스 S, ALL TV 2.0

안녕하세요? 좋은 앱 만들어 주셔서 감사합니다.
ALL TV 정말 잘 사용하고 있습니다!

1. EBS 2가 FHD 화질에서 "시스템 점검 안내"라고 나오면서 재생되지 않습니다. HD 화질에서는 방송이 나오는 것을 확인하였습니다. 

2. 크게 불편한 사항은 아니지만 SBS 파워FM과 SBS 러브FM이 서로 바뀌어 나옵니다. 오류인 것 같아 건의해 봅니다.

다시 한번 좋은 앱 정말 감사합니다.

**Comment by PYTHONKOR** [comment]
아래와 같은 답변 드립니다.

1. 적어주신 것처럼 EBS2가 FHD 송출을 안 하고 있습니다. 따라서 현재로써는 시청을 위해서 HD로 설정을 하고 보시는 방법밖에 없습니다.

2. 라디오 관련 재생 정보는 웨이브에서 가져오는 정보를 바탕으로 설정이 됩니다. 관련된 부분은 웨이브 측에서 데이터로 바뀌어서 설정이 된 것으로 보입니다.

**Comment by ganoyi** [comment]
바쁘신데 답변 감사합니다!

**Comment by PYTHONKOR** [comment]
적어주신 내용을 바탕으로 좀 더 개설한 부분이 있으면 찾아서 추후에 반영하도록 하겠습니다.
