### ISSUE TITLE
Wavve 재생중 멈춤 문제

### ISSUE THREAD

**Issue by jshsakura** [PYTHONKOR/alltv#24]
안녕하세요.
쉴드 Tv 2세대 안드로이드 8.1에서 웨이브 기본결제 (구 옥수수 이관계정)을 통해 공중파 실시간 시청시
간혹 화면이 멈추는 문제가있습니다.

채널이동 등으로 다시 돌아오면 해결이되는데
비슷한 보고가있었는지 궁금합니다.

화질은 설정은 Full hd설정입니다.

이런 훌륭한 앱을 만들어주셔서 거듭 감사드립니다.

**Comment by onlee123** [comment]
저도 같은증상입니다
뷰잉사용중이구요 계정상태와 화질설정은 위와 같습니다.

좋은어플 만들어주셔서 너무 감사합니다

**Comment by PYTHONKOR** [comment]
관련하여 답변 드립니다.

드물게 멈춤 현상을 보고해 주셨는데요. 해당 부분은 문제 추적에 많은 어려움이
있을 것으로 보입니다. 공식앱이 아니다보니, 앱 내에서 처리할 수 없는
부분도 있을 수도 있고요. 관련하여 계속 예의주시는 하도록 하겠습니다.

**Comment by onlee123** [comment]
제작자님 도움이될까 싶어 좀더 겪은상황을 상세히 전달드립니다.
 이 멈춤현상이 저같은경우에는 드물게가 아니라 계속 발생했었습니다. 마치 컴터 켜놓고 아무것도 안하고있으면 일정시간후에 화면보호기가 켜지는것 처럼 채널을 틀어놓고 일정시간이지나면 멈춰버리고 채널 변경하면은 또 잘나오더라구요. 그러다가 일정시간 후에 또 멈추구요. 시간은 한 십분이상이였던걸로 기억합니다.

**Comment by PYTHONKOR** [comment]
화면이 꺼진다는 것인가요?
아니면 영상이 멈춘다는 것인가요?

**Comment by onlee123** [comment]
영상이 멈춥니다.

**Comment by jshsakura** [comment]
디버그를 위해 안드로이드 스튜디오를 설치했습니다.
웹 개발자라 안드가익숙치않아서 살짝헤맸습니다.
디버그하실때 실기를 연결하시나요?
아님 에뮬레이터를 쓰실까요?

**Comment by PYTHONKOR** [comment]
에뮬레이터만 사용해서 개발하였습니다.

**Comment by firstsp** [comment]
SKT 기본 결제면 화질이 HD로 알고 있는데 Full HD로 시청하면 15분 후 멈추는 걸로 들은것 같네요.

**Comment by PYTHONKOR** [comment]
> SKT 기본 결제면 화질이 HD로 알고 있는데 Full HD로 시청하면 15분 후 멈추는 걸로 들은것 같네요.

맞습니다. 자신이 가입된 상품에서 제공하는 화질을 선택하고 재생해야 합니다.
그 이상 화질을 선택하면 일정시간 후에 멈춥니다.(각 서비스 제공자에서 영상 제공 안 됨)

**Comment by jshsakura** [comment]
앗 지금 확인했습니다.
집에가면 바로 확인해보도록 하겠습니다.
주말에 그것이 알고싶다 시청중 끊김이 없었는데 혹 HD설정인지 확인해보겠습니다.

**Comment by jshsakura** [comment]
기존이 FullHD설정이었나 봅니다. HD설정변경후 문제없음을 확인했습니다.
다시한번 좋은 프로그램 만들어주셔서 감사합니다!
