### ISSUE TITLE
로그인 저장이 안되는데요.

### ISSUE THREAD

**Issue by astromo79** [PYTHONKOR/alltv#3]
만들어주신 smartTV 어플이 사용자 편의성이 좋아서 시험적으로 사용을 해보았습니다. 
우선 이런 유용한 어플을 만들어주신 개발자님께 감사드립니다. 
그런데, 아이디에 따라 로그인 저장이 되기도 하고, 안되기도 합니다. 
제꺼로느 푹,옥수수 모두 로그인 저장이 잘 안됩니다. 
특히 푹은 유료결재를 해서 쓰는 아니디는 저장이 안되고 유료결재를 하지 않은 아내 아이디는 저장이 되는통에 실질적인 사용을 못하고 있는데요.
무슨 오류인지 잘 모르겠지만 수정이 가능하다면 좋을것 같아 이렇게 글을 남겨드립니다. 
고맙습니다.

**Comment by PYTHONKOR** [comment]
안녕하세요. 문의에 답변 드립니다.

아래와 같은 정보를 더 요청드립니다.

1. 현재 사용하고 계신 기기가 무엇인지, 또 안드로이드TV 버전이 몇인지
2. 사용하고 계신 ID나 암호에 특수문자가 있는지(예전에 특수문자 관련 문제가 있던적이 있어서)
3. 특수한 계정을 사용하고 계신게 아닌지(각 사이트에서 가입한 계정이 아니라 소셜 계정으로
연동된 계정인지)
4. 안드TV 기본 리모컨 조작이 아니라 키보드나 마우스 조작인지 여부
5.  releases 에 최신 버전 사용 유무

위 부분에 대해 추가적인 답변 요청드려요.

그리고 알고 계시겠지만, 이 앱은 공식앱이 아니고 치팅을 통해 영상 주소를 얻어와
재생하는 방식입니다. 따라서 제가 수정하거나 개선할 부분은 당연히 작업을 하겠지만,
그 외에 부분에 있어서 100% 완벽하게 동작이 보장되지 않습니다.

**Comment by astromo79** [comment]
먼저 빠른 답장에 감사드립니다. 
제가 지방 출장중이라 현재 소유하고 있는 기기에 대한 정확한 기재를 할수 없어서 알고 있는 수준으로 답변을 드리겠습니다. 
 
1. 보유기기 : CJ 헬로 뷰잉 (최신 업데이트버전이나 현재 미확인)
2~3. 암호에 특수 문자 # 표기되어 있음. 
      우선 현재 사용하는 푹 아이디의 경우 비용절감을 위해 아이디,비번을 공유하고 있어 소셜 계정 연동여부가 확인 불가.
4. 안드TV 기본 리모컨 조작중.
 
이렇게 적다보니 암호 문제인 것 같긴하네요. 
2~3번 부분이 사실상 제가 통제할 수 없는 부분이라 원하시는 내용에 답변을 드리지 못해 해결에 큰 도움이 되지 못할 것 같습니다.
저렴한 비용에 타인의 아이디를 공유하고 있는 현실에선 해당 프로그램을 사용하지 못할 것도 같아 아쉽긴 하네요.....
 
그렇지만 제작자분님의 빠른 피드백과 열정에 감동을 받았습니다. ~~^^
무명의 대중에게도 열정적으로 대해주시는 모습을 보니, 앞으로도 하시는 일들이 모두 잘 되길 거라 생각이 듭니다. 
감사합니다. 
 
-----Original Message-----

**Comment by PYTHONKOR** [comment]
적어주신 답변을 바탕으로 다시 답글을 남겨봅니다.

암호에 특수문자가 문제가 되지는 않을 것 같습니다.
이전에 특수문자 문제가 있어서 수정을 하였고, 혹시 싶어 확인차 다시 질문을 했던 부분입니다.

아무래도 의심가는 부분은 소셜 로그인을 사용하는 계정 연동 문제이거나,
다수의 인원이 같이 한 계정을 사용하고 계시는 것 같은데 이 부분이 문제가 되는 것 같습니다. 
공식앱이 아니라 위 문제에 대해서는 제가 아는 한도내에서는
아쉽게도 대처할 방법이 현재로써는 없습니다.

만약 추후 다른 방법을 알게된다면, 반영토록 하겠습니다.
