### ISSUE TITLE
Pooq 채널 Kid채널이 대부분 안됩니다.

### ISSUE THREAD

**Issue by Brunfelsia** [PYTHONKOR/alltv#4]
반갑습니다. 프로그램 제작자님께 다시한번 깊은 감사를 드립니다.
아주 유용하게 사용하고 있습니다.

사용중 모든 부분에 대해 굉장히 만족스러우나..
POOQ의 KID채널의 대부분이 점검중으로 화면문구가 뜹니다.
(EBS KID.. 등..)
신호를 못찾는건 아닌데.. 점검중이라고 나오네요. 다른채널은 모두 정상입니다.
혹시해서, 로그아웃도 해보고, 화질도 바꿔서 해보고 해도 여전히 점검중이라 뜹니다.
PC에서는 정상적으로 출력이 되네요..  ALL TV에서만 이상하게 점검중으로만 계속 뜹니다.
저만 그런가 싶어서 카페에 질문을 하니 동일증상 사용자가 있습니다.
노고스럽지만, 확인 가능할까요?

**Comment by PYTHONKOR** [comment]
안녕하세요. 문의에 답변 드립니다.

우선, 해당 부분에 대해서는 이미 다른 보고를 통해 인지는 하고 있습니다.
제가 가진 계정으로는 무료계정에서 정상작동, 유료결제 계정도 정상 시청이 가능합니다.
아마 키즈 채널이 안나오시는 분들은 뭔가 공통적인 환경이나 계정 설정이 있는 것으로
보여집니다. 해당 부분은 제가 그 환경에 있는 것이 아니라 어떻게 손쓸수가 없는
상황이네요.

그리고 알고 계시겠지만, 이 앱은 공식앱이 아니고 치팅을 통해 영상 주소를 얻어와
재생하는 방식입니다. 따라서 제가 수정하거나 개선할 부분은 당연히 작업을 하겠지만,
그 외에 부분에 있어서 100% 완벽하게 동작이 보장되지 않음을 인지 부탁드려요.
