### ISSUE TITLE
로그인이 안됩니다

### ISSUE THREAD

**Issue by zero7859** [PYTHONKOR/alltv#5]
이렇게 좋은 앱 만들어주셔서 감사합니다.
다름이 아니라, 앱 설치 후 각 서비스에 로그인을 하려는데
맞는 아이디와 비밀번호를 입력해도 자꾸 다시 한번 더 확인 해달라고 뜹니다. 

두 서비스 모두 동일 증상이라, 시청을 못하고 있습니다.
기기는 미박스3S이며, 앱 버전은 1.4/1.3 모두 동일 증상입니다.

비밀번호를 알파벳+숫자로 구성해도 동일합니다.

**Comment by PYTHONKOR** [comment]
아래 내용 확인해 주세요.

1. USB 키보드 사용유무(현재 테스트가 안 된 상태라 키보드로 입력하면 안될수도 있습니다.)
2. 안드TV 리모컨만 사용해서 다음과 같은 스텝으로 해주세요. 아이디 및 암호 입력후에 뒤로가기키를
사용해보세요. 그러면 가상키보드 창이 내려가면서 입력된 상태로 저장을 해보세요.

이 방법도 안되면, 정확하게 어떤 스텝으로 아이디 및 암호 입력을 시도했는지, 다시 정확하게
남겨주세요.

**Comment by PYTHONKOR** [comment]
한가지 더 확인 사항은.. 이게 공식앱이 아니라 각 사이트에서 정식 가입한 계정만 지원합니다.
소셜 로그인을 통한 로그인은 지원이 안됩니다.
