### ISSUE TITLE
HD해상도 이상에서는 멈춥니다

### ISSUE THREAD

**Issue by DrDavidKim** [PYTHONKOR/alltv#6]
SD 해상도로 설정하고 시청하면 계속 잘 나옵니다.
그러나 HD나 FHD 해상도로 설정하고 시청시 5분에서 20분후에 영상이 멈춥니다.
기기는 뷰잉과 미박스3 동일하게 발생합니다.

**Comment by PYTHONKOR** [comment]
시청하는 것이 푹인지 옥수수인지 모르겠지만,
사용하고 계신 유료상품이 해당 화질을 볼 수 없는 상품인것으로 보입니다.

시청할 각 화질에 맞춘 적절한 요금제에 가입하셔야 전체 기능을 쓸 수 있습니다.
가입하신 요금제를 확인해 보세요.

무료계정으로 쓰시는거면 안 나오는게 맞습니다.
