### ISSUE TITLE
옥수수 아이디 입력후 에러가...

### ISSUE THREAD

**Issue by ajhans67** [PYTHONKOR/alltv#8]
안녕하세요. 
미박스 사용자 입니다. 

POOQ은 괜찮은데 옥수수는 아이디 비번 입력후 설정저장을 누르면 
앱이 팅겨져 나가고 설정저장도 안됩니다.
미박스가 두대라 확인 해보니 둘다 같은 증상입니다. 
재부팅 하고 재인스톨 하고 몇번을 시도해도 마찬가지 입니다. 
(이전 버전은 문제가 없었습니다. 소셜 연동 계정도 아닙니다. )

확인 부탁 드립니다. 

- 친구에게 뷰잉을 빌려와 테스트 해보니깐 뷰잉에서는 그런 증상이 없군요 T T

**Comment by PYTHONKOR** [comment]
사용하시는 버전이 어떻게 되시는지요? 현재 1.5 버전을 어제(19.07.13) 릴리즈 했는데,
만약 1.5 버전이시라면 1.4 버전으로 낮춰서 다시 설치해 보시는 것을 권해드리고요.

그리고 이 앱은 정식앱이 아니라 소셜로그인을 지원하지 않습니다.(페북, 카카오등)
각 사이트에서 정식으로 만든 아이디만 로그인이 가능하다는 얘기입니다.
이 부분도 확인해 보시면 될 것 같습니다.

**Comment by PYTHONKOR** [comment]
아래 내용 확인 부탁드립니다.

1. 문제가 발생하는 버전과 잘 되는 버전을 적어주세요.
2. id나 암호에 특수문자가 들어가는지.
3. 아이디 암호 입력 과정을 자세하게 한스텝씩 적어주세요(재현 방법을 찾기 위해)

이전 버전에서는 잘 되었다는 얘기를 적어주셨는데, 우선은 이전 버전으로 사용을 해보세요.
각 버전 업데이트는 마이너 업데이트만 있어서 큰 기능의 차이는 없습니다.
자세한 정보를 남겨주시면 수정을 해보도록 하겠습니다.
